version: "3"

services:
  app:
    build: .
    ports:
      - "80:80"
    container_name: app
    restart: always
    volumes:
      - "./www:/var/www/html"
      - "./php.ini-development:/usr/local/etc/php/php.ini"
      - "./logs/apache:/var/log/apache2"
    links:
      - dbhost:dbhost
      - mail:mail
    environment:
      PHP_SITE_NAME: dev
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable or 0 to desable.

  dbhost:
    image: mysql
    container_name: dbhost
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: dbbase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./.runtime/mysql:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    environment:
      PMA_HOST: dbhost
      PMA_USER: dbuser
      PMA_PASSWORD: dbpass
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    restart: always
    ports:
     - 8001:80
    volumes:
     - /sessions

  mail:
    image: mailhog/mailhog
    container_name: mail
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
