version: '3'

volumes:
  wordpress-mysql-data:
    driver: local

services:
  app:
    build: .
    ports:
      - "80:80"
    container_name: ${APP_NAME}-app
    restart: always
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./php.ini-development:/usr/local/etc/php/php.ini
      - ./.runtime/logs/apache:/var/log/apache2
    links:
      - ${DB_HOST}
      - ${MAIL_LINK}

  dbhost:
    image: ambientum/mysql:5.7
    container_name:  ${APP_NAME}-dbhost
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_BASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - wordpress-mysql-data:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name:  ${APP_NAME}-mail
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
